export enum EventConstant {
    TOUCH_START = "touchstart",
    TOUCH_MOVE = "touchmove",
    POINTER_DOWN = "pointerdown",
    TOUCH_END = "touchend",
    POINTER_OVER = "pointerover",
    POINTER_OUT = "pointerout",
    POINTER_UP = "pointerup",
    MOUSE_UP = "mouseup",
    CLICK = "click"
}

export enum CustomEventConstant {
    SHOW_LOADING_SCREEN = "SHOW_LOADING_SCREEN",
    HIDE_LOADING_SCREEN = "HIDE_LOADING_SCREEN",
    RESET_ON_PRESENTATION_COMPLETE = "RESET_ON_PRESENTATION_COMPLETE",
    SHOW_NEW_CARDS = "SHOW_NEW_CARDS",
    SHOW_WIN_PRESENTATION = "SHOW_WIN_PRESENTATION",
    HIDE_WIN_PRESENTATION = "HIDE_WIN_PRESENTATION",
    START_GAME = "START_GAME",
    BET_PLACED = "BET_PLACED",
    SHOW_HIDE_HELPER_TXT = "SHOW_HIDE_HELPER_TXT",
    ENABLE_DISABLE_BUTTONS = "ENABLE_DISABLE_BUTTONS",
    DISABLE_COIN = "DISABLE_COIN",
    UPDATE_METER_ON_RESULT = "UPDATE_METER_ON_RESULT"

}